import React, { useState } from 'react'
import { PlayCircle } from 'lucide-react'
import { VIDEO_ASSETS, videoPoster, videoUrl } from '../data/gallery'
import { IMAGES } from '../data/images'

interface VideoReelProps {
  /** Which video from the sim2u-video tag to show. 0 is the newest. */
  index?: number
  title: string
  /**
   * Shown under the player — and ONLY when a video actually exists. A caption
   * describing footage that is not there reads as a broken page, and this is
   * not the place for notes to ourselves: whatever goes here is public.
   */
  caption?: string
}

/**
 * Plays a video straight from Cloudinary.
 *
 * TO ADD A REEL: tag a video `sim2u-video` in Cloudinary. It appears here on
 * the next build, poster frame included, generated by Cloudinary from the first
 * frame of the video itself. Until one is tagged this renders a tidy
 * placeholder rather than a broken player.
 *
 * That instruction lives in this comment on purpose. It used to be passed in as
 * the `caption` prop, which meant every visitor to the home page and the
 * gallery was reading "Tag a video sim2u-video in Cloudinary".
 *
 * The <video> element is only mounted after a click, so an unplayed reel costs
 * nothing in page weight or Core Web Vitals.
 */
const VideoReel: React.FC<VideoReelProps> = ({ index = 0, title, caption }) => {
  const [playing, setPlaying] = useState(false)
  const asset = VIDEO_ASSETS[index]

  return (
    <figure className="relative m-0">
      <div className="relative rounded-[40px] overflow-hidden shadow-[0_50px_100px_-20px_rgba(33,54,49,0.4)] aspect-video bg-mountainGreen">
        {playing && asset ? (
          <video
            className="absolute inset-0 w-full h-full object-cover"
            src={videoUrl(asset)}
            poster={videoPoster(asset)}
            controls
            autoPlay
            playsInline
          />
        ) : (
          <>
            <img
              src={asset ? videoPoster(asset) : IMAGES.videoPosterFallback}
              alt={title}
              className="absolute inset-0 w-full h-full object-cover"
              loading="lazy"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-mountainGreen/90 via-mountainGreen/30 to-transparent" />

            <button
              type="button"
              onClick={() => setPlaying(true)}
              disabled={!asset}
              className="absolute inset-0 flex flex-col items-center justify-center gap-5 group disabled:cursor-default"
              aria-label={asset ? `Play ${title}` : 'Video reel coming soon'}
            >
              <span className="w-24 h-24 rounded-full bg-gold/90 text-mountainGreen flex items-center justify-center shadow-2xl transition-transform group-hover:scale-110 group-disabled:group-hover:scale-100">
                <PlayCircle size={48} />
              </span>
              <span className="text-white font-black uppercase tracking-[0.3em] text-xs">
                {asset ? 'Watch the reel' : 'Reel coming soon'}
              </span>
            </button>
          </>
        )}
      </div>

      {caption && asset && (
        <figcaption className="text-center text-gray-500 text-sm mt-6 italic">
          {caption}
        </figcaption>
      )}
    </figure>
  )
}

export default VideoReel
